### ISSUE TITLE
Information about `volume`

### ISSUE THREAD

**Issue by Jokero** [jidu0106/mock-stock-data#1]
First of all, thanks for the nice library.

The candlestick chart is often referred to as the `OHLC` or `OHLCV` chart where `V` means `volume`. 

Currently, the library does not generate a value for volume. It would be nice to have it in addition to open, high, low and close values

**Comment by cyberfury10** [comment]
Hi @Jokero 
Thank you for the suggestion. Kindly check the latest version, I have handled the volume in #2.
